markdown: rdiscount
safe: true
lsi: false
pygments: true
permalink: /posts/:title
title : Carlos Becker
production_url : http://carlosbecker.com
description: "Througths, tutorials, hacks and other things by Carlos Alexandro Becker."
disqus_shortname: caarlos0blog
# analytics: UA-32899481-1
gauges: 50f1f940613f5d2cfe000026
exclude: [ Gemfile, Gemfile.lock, gems ]
author :
  name : Carlos Alexandro Becker
  github : caarlos0
  twitter : caarlos0
  email: caarlos0@gmail.com
